import type { Question } from "./question-card";

export const allQuestions: Question[] = [
  {
    id: "1",
    title:
      "How to join 2 columns in a data set to make a separate column in SQL",
    description:
      "I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combineI do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combineI do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combineI do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combineI do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine I do not know the code for it as I am a beginner. As an example what I need to do is like there is a column 1 containing First name, and column 2 consists of last name I want a column to combine ",
    tags: ["SQL", "Data", "Beginner", "Join"],
    user: "Adnan Arodiya",
    answers: 5,
    votes: 12,
    views: 234,
    timestamp: "5 hours ago",
    isAnswered: true,
    difficulty: "beginner",
  },
  {
    id: "2",
    title: "How to use React Context for global state?",
    description:
      "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    tags: ["React", "Context"],
    user: "Usman Sabuwala",
    answers: 3,
    votes: 8,
    views: 156,
    timestamp: "3 hours ago",
    isAnswered: false,
    difficulty: "intermediate",
  },
  {
    id: "3",
    title: "How to optimize a slow API call?",
    description:
      "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    tags: ["API", "Performance", "Optimization"],
    user: "Hussain Gagan",
    answers: 2,
    votes: 24,
    views: 892,
    timestamp: "2 hours ago",
    isAnswered: true,
    difficulty: "advanced",
  },
  {
    id: "4",
    title: "Best practices for TypeScript interfaces",
    description:
      "I'm learning TypeScript and want to understand the best practices for creating interfaces. What are some common patterns and anti-patterns?",
    tags: ["TypeScript", "Interfaces", "Best Practices"],
    user: "Sarah Johnson",
    answers: 8,
    votes: 45,
    views: 1234,
    timestamp: "8 hours ago",
    isAnswered: true,
    difficulty: "intermediate",
  },
  {
    id: "5",
    title: "How to implement authentication with JWT tokens?",
    description:
      "I need to implement user authentication in my Node.js application using JWT tokens. Can someone provide a step-by-step guide?",
    tags: ["Node.js", "JWT", "Authentication", "Security"],
    user: "Mike Chen",
    answers: 12,
    votes: 67,
    views: 2156,
    timestamp: "12 hours ago",
    isAnswered: true,
    difficulty: "advanced",
  },
  {
    id: "6",
    title: "CSS Grid vs Flexbox: When to use which?",
    description:
      "I'm confused about when to use CSS Grid and when to use Flexbox. Can someone explain the differences and use cases?",
    tags: ["CSS", "Grid", "Flexbox", "Layout"],
    user: "Emily Davis",
    answers: 6,
    votes: 34,
    views: 678,
    timestamp: "6 hours ago",
    isAnswered: true,
    difficulty: "intermediate",
  },
  {
    id: "7",
    title: "How to deploy a React app to Vercel?",
    description:
      "I've built a React application and want to deploy it to Vercel. What are the steps involved and any common issues to watch out for?",
    tags: ["React", "Vercel", "Deployment", "Frontend"],
    user: "Alex Thompson",
    answers: 4,
    votes: 19,
    views: 445,
    timestamp: "4 hours ago",
    isAnswered: false,
    difficulty: "beginner",
  },
  {
    id: "8",
    title: "Database normalization explained",
    description:
      "I'm studying database design and need help understanding normalization. Can someone explain the different normal forms with examples?",
    tags: ["Database", "SQL", "Normalization", "Design"],
    user: "David Wilson",
    answers: 9,
    votes: 56,
    views: 1567,
    timestamp: "1 day ago",
    isAnswered: true,
    difficulty: "advanced",
  },
  {
    id: "9",
    title: "How to handle errors in async/await functions?",
    description:
      "I'm using async/await in my JavaScript code but I'm not sure about the best way to handle errors. What are the recommended patterns?",
    tags: ["JavaScript", "Async/Await", "Error Handling"],
    user: "Lisa Brown",
    answers: 7,
    votes: 28,
    views: 789,
    timestamp: "10 hours ago",
    isAnswered: true,
    difficulty: "intermediate",
  },
  {
    id: "10",
    title: "Setting up a CI/CD pipeline with GitHub Actions",
    description:
      "I want to set up continuous integration and deployment for my project using GitHub Actions. Can someone provide a basic workflow example?",
    tags: ["GitHub Actions", "CI/CD", "DevOps", "Automation"],
    user: "Robert Garcia",
    answers: 5,
    votes: 41,
    views: 923,
    timestamp: "7 hours ago",
    isAnswered: false,
    difficulty: "advanced",
  },
  {
    id: "11",
    title: "How to implement dark mode in a web app?",
    description:
      "I want to add dark mode functionality to my web application. What are the best approaches for implementing this feature?",
    tags: ["CSS", "Dark Mode", "UI/UX", "JavaScript"],
    user: "Jennifer Lee",
    answers: 11,
    votes: 73,
    views: 1845,
    timestamp: "2 days ago",
    isAnswered: true,
    difficulty: "intermediate",
  },
  {
    id: "12",
    title: "Understanding React hooks: useEffect vs useState",
    description:
      "I'm learning React hooks and I'm confused about when to use useEffect vs useState. Can someone explain the differences?",
    tags: ["React", "Hooks", "useEffect", "useState"],
    user: "Kevin Martinez",
    answers: 6,
    votes: 22,
    views: 567,
    timestamp: "9 hours ago",
    isAnswered: true,
    difficulty: "beginner",
  },
  {
    id: "13",
    title: "How to optimize images for web performance?",
    description:
      "I want to improve my website's loading speed by optimizing images. What are the best practices and tools for image optimization?",
    tags: ["Performance", "Images", "Web Optimization", "SEO"],
    user: "Amanda White",
    answers: 8,
    votes: 39,
    views: 1123,
    timestamp: "14 hours ago",
    isAnswered: true,
    difficulty: "intermediate",
  },
  {
    id: "14",
    title: "Building a RESTful API with Express.js",
    description:
      "I'm building a REST API with Express.js and want to follow best practices. Can someone provide a comprehensive guide?",
    tags: ["Express.js", "REST API", "Node.js", "Backend"],
    user: "Chris Anderson",
    answers: 10,
    votes: 58,
    views: 1689,
    timestamp: "1 day ago",
    isAnswered: true,
    difficulty: "advanced",
  },
  {
    id: "15",
    title: "How to implement infinite scrolling?",
    description:
      "I want to implement infinite scrolling in my React application. What are the best approaches and libraries to use?",
    tags: ["React", "Infinite Scroll", "Performance", "UX"],
    user: "Rachel Green",
    answers: 4,
    votes: 16,
    views: 334,
    timestamp: "5 hours ago",
    isAnswered: false,
    difficulty: "intermediate",
  },
];
